name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "My first GitHub Actions Job"

        - name: List Files
          run: ls
        
        - name: Find README anywhere
          run: |
            find . -maxdepth 5 -iname "readme*"
            echo "Top-level files:"
            find . -maxdepth 2 -type f -print

        - name: Read the file
          run: cat README.md

